name: Compile Arctica CI

on:
  push:
    branches: [ "main", "actionstest" ]
  pull_request:
    branches: [ "main", "actionstest" ]

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build-arctica:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 12.22.9, 14.x, 14.6.0]

    steps:
      - name: Checkout repository and submodules
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Compile the frontend submodule
        run: |
          cd arctica-frontend/
          npm ci
          npm run build --verbose --if-present
          cd ../

      - name: Install the Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - name: Install backend dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.0-dev libgtk-3-dev

      - name: Check for rust errors
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --verbose

      - name: Compile the backend code
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --verbose
